nelmio_api_doc:
    documentation:
        info:
            title: Tindart
            description: This is an awesome app!
            version: 1.0.0
        securityDefinitions:
            Token:
                type: apiKey
                description: 'Value: {token}'
                name: X-AUTH-TOKEN
                in: header
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc(.json)?$) # Accepts routes under /api except /api/doc
