places:
  type: rest
  resource: App\Controller\PlaceController

users:
  type: rest
  resource: App\Controller\UserController

login:
  methods: [POST]
  path: /login
  controller: App\Controller\AuthenticationController:postLoginAction