places:
  type: rest
  resource: App\Controller\PlaceController

users:
  type: rest
  resource: App\Controller\UserController

events:
  type: rest
  parent: places
  resource: App\Controller\EventController

login:
  methods: [POST]
  path: /login
  controller: App\Controller\AuthenticationController:postLoginAction